version: "3"

services:
  trading_view_connector:
    container_name: trading_view_connector
    build:
      context: ./
    network_mode: "host"
    restart: always
    volumes:
      - .:/app
      - /app/.venv

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=connector
    ports:
      - '5432:5432'
