version: "3"

services:
  trading_view_connector:
    container_name: trading_view_connector
    build:
      context: ./
    ports:
      - "80:80"
    restart: always
    volumes:
      - .:/app
      - /app/.venv

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=connector
    ports:
      - '5432:5432'
    volumes:
      - data_postgres:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - data_redis:/data

volumes:
  data_redis:
    driver: local

  data_postgres:
    driver: local
