"""update_deals_table_add_position

Revision ID: 3d9358bcf686
Revises: 900e1be8f4c6
Create Date: 2023-06-28 21:50:47.237178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9358bcf686'
down_revision = '900e1be8f4c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('position', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
