"""update_bots_table_add_exchange_id

Revision ID: 8608a0933e2d
Revises: 7375f7f0306b
Create Date: 2023-05-25 19:13:42.798924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8608a0933e2d'
down_revision = '7375f7f0306b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('exchange_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
