"""update_exchanges_table_add_hedge

Revision ID: 0c80af381491
Revises: 3d9358bcf686
Create Date: 2023-07-08 13:07:08.937421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c80af381491'
down_revision = '3d9358bcf686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchanges', sa.Column('hedge', sa.Boolean(), nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
