"""update bots table add copy bot id

Revision ID: ff229a7a3d8f
Revises: de483b161b28
Create Date: 2023-05-13 22:24:06.148031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff229a7a3d8f'
down_revision = 'de483b161b28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('copy_bot_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
