"""empty message

Revision ID: 7e438348d5aa
Revises: 1d3b7e8e4e96
Create Date: 2023-04-23 21:38:58.407163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e438348d5aa'
down_revision = '1d3b7e8e4e96'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
