"""0.1.0

Revision ID: b4aaabb4278e
Revises: cb0c87169654
Create Date: 2023-03-04 14:28:31.423577

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b4aaabb4278e'
down_revision = 'cb0c87169654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'exchange_id')
    op.add_column('deals', sa.Column('bot_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
