"""0.1.0

Revision ID: cb0c87169654
Revises: 
Create Date: 2022-12-30 20:06:10.445304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb0c87169654'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pair', sa.String(length=255), nullable=False),
    sa.Column('exchange_id', sa.String(length=255), nullable=False),
    sa.Column('safety_order_count', sa.SmallInteger(), nullable=False, default=0),
    sa.Column('date_open', sa.Integer(), nullable=False),
    sa.Column('date_close', sa.Integer(), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_id'), 'deals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deal_id'), table_name='deals')
    op.drop_table('deals')
    # ### end Alembic commands ###
